#### sklearn.preprocessing.LabelEncoder
* class sklearn.preprocessing.LabelEncoder

In [7]:
from sklearn.preprocessing import LabelEncoder

# LabelEncoder를 객체로 생성한 후, fit과 transform으로 label 인코딩 수행
items = ['TV','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder = LabelEncoder()


labels = encoder.fit_transform(items)
print(f'인코딩 변환값 : {labels}')
print('인코딩 클래스 : ', encoder.classes_)

인코딩 변환값 : [0 3 4 2 2 1 1]
인코딩 클래스 :  ['TV' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [9]:
encoder.inverse_transform([1,1,1,2,3,4])

array(['믹서', '믹서', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

#### sklearn.preprocessing.OneHotEncoder
* class sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None)

In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# items = [1,2,3,4,4,5,5]
items = [['TV', 1],['전자렌지', 2],['컴퓨터', 3],['선풍기', 4],['선풍기', 4],['믹서', 5],['믹서',5]]



# items = np.array(items).reshape(1, -1)
o_encoder = OneHotEncoder()
o_encoder.fit(items)
o_labels = o_encoder.transform(items)
print('원-핫 인코딩 데이터')
print(o_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(o_labels.shape)

원-핫 인코딩 데이터
[[1. 1. 1. 1. 1. 1. 1.]]
원-핫 인코딩 데이터 차원
(1, 7)


In [21]:
items = ['TV','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환
labels = labels.reshape(-1, 1)

# 원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원 - 핫 인코딩 데이터 : ', oh_labels.toarray())
print('원 - 핫 인코딩 데이터 차원 : ', oh_labels.shape)

원 - 핫 인코딩 데이터 :  [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
원 - 핫 인코딩 데이터 차원 :  (7, 5)


In [32]:
import pandas as pd

df = pd.DataFrame({'items' : ['TV','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df['items'])
# pd.get_dummies(df['items']).iloc[:, 0]

TV  믹서  선풍기  전자렌지  컴퓨터
0   1   0    0     0    0
1   0   0    0     1    0
2   0   0    0     0    1
3   0   0    1     0    0
4   0   0    1     0    0
5   0   1    0     0    0
6   0   1    0     0    0